public class operadores {
    public static void main (String[] args){
        var a = 3;
        var b = 2;
        var c = a + b;
        System.out.println("c = " + c);
        c = a - b;
        System.out.println("c = " + c);
        c = a * b;
        System.out.println("c = " + c);
        c = a / b;
        System.out.println("c = " + c);
        c = a % b;
        System.out.println("c = " + c);
        c = a + 1;
        System.out.println("c = " + c);
        c++;
        System.out.println("c = " + c);
        c--;
        System.out.println("c = " + c);
        c += 2;
        System.out.println("c = " + c);
        c -= 2;
        System.out.println("c = " + c);
        c *= 2;
        System.out.println("c = " + c);
        c /= 2;
        System.out.println("c = " + c);
        c %= 2;
        System.out.println("c = " + c);
        c = a + b * c;
        System.out.println("c = " + c);
        c = (a + b) * c;
        System.out.println("c = " + c);
        c = a + b / c;
        System.out.println("c = " + c);
        c = (a + b) / c;
        System.out.println("c = " + c);
        c = a + b % c;
        System.out.println("c = " + c);
        c = (a + b) % c;
        System.out.println("c = " + c);
        c = -a;
        System.out.println("c = " + c);
        c = +a;
        System.out.println("c = " + c);
        c = a++;
        System.out.println("c = " + c);
        c = ++a;
        System.out.println("c = " + c);
        c = a--;
        System.out.println("c = " + c);
        c = --a;
        System.out.println("c = " + c);
        c = a + 5 - 3;
        System.out.println("c = " + c);
        c = a + 5 - 3 * 2;
        System.out.println("c = " + c);
    }
}
